Models/Submission.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models
{
    public class Submission
    {
        public int ID { get; set; }

        [Required]
        public int AssignmentID { get; set; }

        [Required]
        public int StudentID { get; set; }

        [Required]
        public string Content { get; set; }

        [Required]
        public string Grade { get; set; }
    }
}

Pages/Courses/Assignments/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using LMS.Data;
using LMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;

namespace LMS.Pages.Courses.CourseInfo.Assignments
{
    public class CreateModel : PageModel
    {
        private readonly LMS.Data.LMSContext _context;

        public CreateModel(LMS.Data.LMSContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Course Course { get; set; }

        [BindProperty]
        public Assignment Assignment { get; set; }

        public SelectList SubmissionList { get; set; }

        public IActionResult OnGet()
        {
            List<SelectListItem> types = new List<SelectListItem>();

            types.Add(new SelectListItem() { Text = "Text Box Entry", Value = "Text Box Entry" });
            types.Add(new SelectListItem() { Text = "File Upload", Value = "File Upload" });

            SubmissionList = new SelectList(types, "Value", "Text");

            return Page();
        }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            int courseID = (int)HttpContext.Session.GetInt32("currCourse");

            await CreateAssignment(courseID);

            return RedirectToPage("./Index");
        }

        public async Task CreateAssignment(int courseID)
        {
            int userID = (int)HttpContext.Session.GetInt32("userID");

            Course = await _context.Course.FirstOrDefaultAsync(m => m.ID == courseID);

            Assignment.CourseID = Course.ID;

            await AddAssignmentCreatedNotification(userID);

            _context.Assignment.Add(Assignment);

            await _context.SaveChangesAsync();
        }

        /// <summary>
        /// Creates a notification for when a new assignment is added to a course.
        /// </summary>
        /// <param name="userID">int userID</param>
        /// <returns>Task</returns>
        private async Task AddAssignmentCreatedNotification(int userID)
        {
            Course course = await _context.Course.FirstOrDefaultAsync(a => a.ID == Assignment.CourseID);
            Department department = await _context.Department.FirstOrDefaultAsync(d => d.ID == Int32.Parse(course.Department));
            Assignment assignment =  await _context.Assignment.FirstOrDefaultAsync(a => a.Description == Assignment.Description);

            string message = "New assignment available: " + department.Code + " " + course.Number + " - " + Assignment.Title;

            List<Registration> registrationRecords = new List<Registration>();
            registrationRecords = _context.Registration.Where(r => r.Course == course.ID).ToList();

            foreach (Registration registration in registrationRecords)
            {
                Notification notification = new Notification()
                {
                    StudentID = registration.Student,
                    AssignmentID = assignment.ID,
                    Message = message,
                };
                _context.Notification.Add(notification);
            }
            await _context.SaveChangesAsync();
        }
    }
}

Pages/Courses/Assignments/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LMS.Data;
using LMS.Models;

namespace LMS.Pages.Courses.CourseInfo.Assignments
{
    public class DeleteModel : PageModel
    {
        private readonly LMS.Data.LMSContext _context;

        public DeleteModel(LMS.Data.LMSContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Assignment Assignment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Assignment = await _context.Assignment.FirstOrDefaultAsync(m => m.ID == id);

            if (Assignment == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Assignment = await _context.Assignment.FindAsync(id);

            if (Assignment != null)
            {
                _context.Assignment.Remove(Assignment);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Courses/Assignments/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LMS.Data;
using LMS.Models;

namespace LMS.Pages.Courses.CourseInfo.Assignments
{
    public class DetailsModel : PageModel
    {
        private readonly LMS.Data.LMSContext _context;

        public DetailsModel(LMS.Data.LMSContext context)
        {
            _context = context;
        }

        public Assignment Assignment { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Assignment = await _context.Assignment.FirstOrDefaultAsync(m => m.ID == id);

            if (Assignment == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/Courses/Assignments/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS.Data;
using LMS.Models;
using Microsoft.AspNetCore.Http;

namespace LMS.Pages.Courses.CourseInfo.Assignments
{
    public class EditModel : PageModel
    {
        private readonly LMS.Data.LMSContext _context;

        public EditModel(LMS.Data.LMSContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Assignment Assignment { get; set; }

        [BindProperty]
        public Course Course { get; set; }

        public SelectList SubmissionList { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            List<SelectListItem> types = new List<SelectListItem>();

            types.Add(new SelectListItem() { Text = "Text Box Entry", Value = "Text Box Entry" });
            types.Add(new SelectListItem() { Text = "File Upload", Value = "File Upload" });

            SubmissionList = new SelectList(types, "Value", "Text");

            Assignment = await _context.Assignment.FirstOrDefaultAsync(m => m.ID == id);

            if (Assignment == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            int courseID = (int)HttpContext.Session.GetInt32("currCourse");
            Course = await _context.Course.FirstOrDefaultAsync(m => m.ID == courseID);

            Assignment.CourseID = Course.ID;

            _context.Attach(Assignment).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AssignmentExists(Assignment.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AssignmentExists(int id)
        {
            return _context.Assignment.Any(e => e.ID == id);
        }
    }
}

Pages/Courses/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using LMS.Data;
using LMS.Models;

namespace LMS.Pages.Courses
{
    public class DeleteModel : PageModel
    {
        private readonly LMS.Data.LMSContext _context;

        public DeleteModel(LMS.Data.LMSContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Course Course { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Course = await _context.Course.FirstOrDefaultAsync(m => m.ID == id);

            if (Course == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Course = await _context.Course.FindAsync(id);

            if (Course != null)
            {
                _context.Course.Remove(Course);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Submission/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LMS.Data;
using LMS.Models;
using Microsoft.AspNetCore.Http;

namespace LMS.Pages.Submission
{
    public class EditModel : PageModel
    {
        private readonly LMS.Data.LMSContext _context;

        public EditModel(LMS.Data.LMSContext context)
        {
            _context = context;
        }

        [BindProperty]
        public LMS.Models.Submission Submission { get; set; }

        public User Student { get; set; }

        public Assignment Assignment { get; set; }

        public Course Course { get; set; }

        public Department Department { get; set; }

        public Registration Registration { get; set; }

        [BindProperty]
        public string Grade { get; set; }

        [BindProperty]
        public bool FileUpload { get; set; }

        public IList<Assignment> Assignments { get; set; }

        public IList<LMS.Models.Submission> Submissions { get; set; }

        public List<double> Totals { get; set; }

        public List<double> Grades { get; set; }

        public double PointsPossible { get; set; }

        public double CourseGrade { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            Submission = await _context.Submission.FirstOrDefaultAsync(x => x.ID == id);

            Student = await _context.User.FirstOrDefaultAsync(u => u.ID == Submission.StudentID);
            Assignment = await _context.Assignment.FirstOrDefaultAsync(u => u.ID == Submission.AssignmentID);
            Course = await _context.Course.FirstOrDefaultAsync(u => u.ID == Assignment.CourseID);
            Department = await _context.Department.FirstOrDefaultAsync(u => u.ID == Int32.Parse(Course.Department));

            if (Submission == null)
            {
                return NotFound();
            }

            // Check for submission type to display proper form
            if (Assignment.SubmissionType == "File Upload")
            {
                FileUpload = true;
            }
            else
            {
                FileUpload = false;
            }

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync(int? id)
        {
            this.Submission = await _context.Submission.FirstOrDefaultAsync(x => x.ID == id);
            HttpContext.Session.SetInt32("currAssignment", Submission.AssignmentID);

            Submission.Grade = Grade;

            //Stores notification in db
            await AddGradedNotification();

            try
            {
                await this.SubmitGrade(Grade, this.Submission);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SubmissionExists(Submission.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            await UpdateTotalGrade(Submission);
            return RedirectToPage("./Index");
        }

        public async Task SubmitGrade(string grade, Models.Submission submission)
        {
            submission.Grade = grade;
            await _context.SaveChangesAsync();
        }

        /// <summary>
        /// Adds a notification when an instructor grades an assignment
        /// </summary>
        /// <returns>Task</returns>
        private async Task AddGradedNotification()
        {
            Assignment assignment = await _context.Assignment.FirstOrDefaultAsync(a => a.ID == Submission.AssignmentID);
            Course course = await _context.Course.FirstOrDefaultAsync(c => c.ID == assignment.CourseID);
            Department department = await _context.Department.FirstOrDefaultAsync(d => d.ID == Int32.Parse(course.Department));

            string message = department.Code + " " + course.Number + " - " + assignment.Title + " has been graded.";

            Notification notification = new Notification()
            {
                StudentID = Submission.StudentID,
                AssignmentID = Submission.AssignmentID,
                Message = message,
            };

            _context.Notification.Add(notification);
        }

        private bool SubmissionExists(int id)
        {
            return _context.Submission.Any(e => e.ID == id);
        }

        public ActionResult OnPostDownloadFile(int? submission)
        {
            Submission = _context.Submission.FirstOrDefault(x => x.ID == submission);
            Assignment = _context.Assignment.FirstOrDefault(x => x.ID == Submission.AssignmentID);
            string newFile;

            int idx = Submission.Content.LastIndexOf('\\');
            if (idx != -1)
            {
                newFile = Submission.StudentID + "_" + Submission.Content.Substring(idx + 1);

                idx = Submission.Content.LastIndexOf("root\\");
                string filePath = Submission.Content.Substring(idx + 5);

                return File(filePath, "application/octet-stream", newFile);
            }
            else
            {
                return Page();
            }
        }

        public async Task UpdateTotalGrade(LMS.Models.Submission sub)
        {
            Student = await _context.User.FirstOrDefaultAsync(u => u.ID == sub.StudentID);
            Assignment = await _context.Assignment.FirstOrDefaultAsync(a => a.ID == sub.AssignmentID);
            Registration = await _context.Registration.FirstOrDefaultAsync(r => r.Student == Student.ID && r.Course == Assignment.CourseID);

            Submissions = await _context.Submission.Where(x => x.StudentID == Student.ID).ToListAsync();
            Assignments = await _context.Assignment.Where(x => x.CourseID == Registration.Course).ToListAsync();

            Totals = new List<double>();
            Grades = new List<double>();

            foreach (var item in Assignments)
            {
                foreach (var submission in Submissions)
                {
                    if (item.ID == submission.AssignmentID)
                    {
                        if (submission.Grade != "--")
                        {
                            double total = item.Points;
                            Totals.Add(total);
                            double grade = Double.Parse(submission.Grade);
                            Grades.Add(grade);
                        }
                    }
                }
            }

            foreach (var item in Totals)
            {
                PointsPossible += item;
            }

            foreach (var item in Grades)
            {
                CourseGrade += item;
            }

            CourseGrade = (CourseGrade / PointsPossible) * 100;

            CourseGrade = Math.Round(CourseGrade, 2);

            Registration.Grade = CourseGrade;

            await _context.SaveChangesAsync();
        }
    }
}

Pages/Submission/Create.cshtml
@page
@model LMS.Pages.Submission.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>@Model.Assignment.Title</h1>

<h4>Points: @Model.Assignment.Points&emsp;Due: @Model.Assignment.Due</h4>
@if (Model.Submitted)
{
    if (Model.Submission.Grade != "--")
    {
        <h4 class="text-success">GRADED:  @Model.Submission.Grade / @Model.Assignment.Points</h4>
    }
    else
    {
        <h4 class="text-success">SUBMITTED</h4>
    }
}
<hr />
<div class="row">
    <div class="col-lg-12">
        <form method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Submission.Content" />
            <div class="form-group">
                @Model.Assignment.Description
            </div>
            @if (!Model.Submitted)
            {
                if (Model.FileUpload)
                {
                    <div class="form-group row col-lg-6">
                        <label asp-for="File" class="col-sm-2 col-form-label">File Upload</label>
                        <div class="col-sm-10">
                            <div class="custom-file">
                                <input asp-for="File" class="custom-file-input form-control" />
                                <label class="custom-file-label">Select File</label>
                            </div>
                        </div>
                    </div>
                }
                else
                {
                    <div class="form-group">
                        <label asp-for="@Model.Content" class="control-label">Text Submission:</label>
                        <textarea rows="10" asp-for="@Model.Content" class="form-control"></textarea>
                        <span asp-validation-for="@Model.Content" class="text-danger"></span>
                    </div>
                }
                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-primary" />
                </div>
            }
            else
            {
                <div class="form-group">
                    <input type="submit" value="Submitted" class="btn btn-secondary" disabled />
                </div>
            }
        </form>
    </div>
</div>

<div id = "container" style = "width: 550px; height: 400px; margin: 0 auto"> </div>

<script type = "text/javascript" src = "https://www.gstatic.com/charts/loader.js"></script>
<script type = "text/javascript">google.charts.load('current', {packages: ['corechart']}); </script>

<script type="text/javascript">

    function drawChart() {
        // Define the chart to be drawn.
        var data = google.visualization.arrayToDataTable([
            ['Percentile', '', { role: 'style'}, { role: 'annotation' }],
            ['<70',  @Model.one, '#FF0000', '@Html.Raw(Model.ann1)'],
            ['70-75',  @Model.two, '#CC0033', '@Html.Raw(Model.ann2)'],
            ['75-80',  @Model.three, '#990066', '@Html.Raw(Model.ann3)'],
            ['80-85',  @Model.four, '#660099', '@Html.Raw(Model.ann4)'],
            ['85-90',  @Model.five, '#3300CC', '@Html.Raw(Model.ann5)'],
            ['90-95',  @Model.six, '#0000FF', '@Html.Raw(Model.ann6)'],
            ['95-100',  @Model.seven, '#000080', '@Html.Raw(Model.ann7)']
        ]);

        var options = {
        title: 'Average: @Model.average',
        legend: {position: 'none'}
        }; 

        // Instantiate and draw the chart.
        var chart = new google.visualization.ColumnChart(document.getElementById('container'));
        chart.draw(data, options);
     }
    google.charts.setOnLoadCallback(drawChart);
</script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

@section Scripts {
    @*This j-query script updates the above label "custom-file-label" to read the file name you selected.*@
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Submission/Delete.cshtml
@page
@model LMS.Pages.Submission.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Submission</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.AssignmentID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.AssignmentID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.StudentID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.StudentID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.Content)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Submission.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Submission/Details.cshtml
@page
@model LMS.Pages.Submission.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Submission</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.AssignmentID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.AssignmentID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.StudentID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.StudentID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Submission.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Submission.Content)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Submission.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Submission/Edit.cshtml
@page
@model LMS.Pages.Submission.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>@Model.Assignment.Title</h1>

<h4>Points: @Model.Assignment.Points&emsp;Due: @Model.Assignment.Due</h4>
<hr />
<div class="row">
    <div class="col-lg-12">
        <form method="post">
            <div class="form-group col-lg-12">
                @Model.Assignment.Description
            </div>
            <h4>Student Submission</h4>
            <div class="form-group col-lg-12">
                @if (!Model.FileUpload)
                {
                    @Model.Submission.Content
                }
                else
                {
                    string fileName = Model.Student.ID.ToString() + "_" + Model.Assignment.Title;
                    <input type="hidden" name="submission" value=@Model.Submission.ID />
                    <input type="submit" value=@fileName asp-page-handler="DownloadFile" class="btn btn-link text-info" />
                }
            </div>
            @if (Model.Submission.Grade == "--")
            {
                <div class="form-group col-lg-2">
                    <label asp-for="@Model.Grade" class="control-label"></label>
                    <input asp-for="@Model.Grade" class="form-control" type="number" min="0" max="@Model.Assignment.Points" step=".01" />
                    <span asp-validation-for="@Model.Grade" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-4">
                    <input type="submit" value="Submit Grade" class="btn btn-primary" />
                </div>
            }
            else
            {
                <div class="form-group col-lg-2">
                    <label asp-for="@Model.Grade" class="control-label"></label>
                    <input asp-for="@Model.Grade" value=@Model.Submission.Grade class="form-control" type="number" min="0" max="@Model.Assignment.Points" step=".01" disabled />
                    <span asp-validation-for="@Model.Grade" class="text-danger"></span>
                </div>
                <div class="form-group col-lg-4">
                    <input type="submit" value="Submitted" class="btn btn-secondary" disabled />
                </div>
            }
        </form>
    </div>
</div>

<div class="col-lg-4">
    <a asp-page="./Index" asp-route-id="@Model.Submission.AssignmentID">Back to Submissions</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Submission/Index.cshtml
@page
@model LMS.Pages.Submission.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Student Submissions</h1>

@*<p>
    <a asp-page="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                Student
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Submission[0].StudentID)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Submission[0].Content)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Submission[0].Grade)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Submission) {
        <tr>
            <td>
                @foreach (var student in Model.Students)
                {
                    if (student.ID == item.StudentID)
                    {
                        var studentName = student.FirstName + ' ' + student.LastName;
                        @Html.DisplayFor(modelItem => studentName)
                        break;
                    }
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentID)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>*@
            <td>
                @Html.DisplayFor(mdoelItem => item.Grade)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID">Grade</a> @*|
                <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>*@
            </td>
        </tr>
}
    </tbody>
</table>

<div id = "container" style = "width: 550px; height: 400px; margin: 0 auto"> </div>

<script type = "text/javascript" src = "https://www.gstatic.com/charts/loader.js"></script>
<script type = "text/javascript">google.charts.load('current', {packages: ['corechart']}); </script>

<script type="text/javascript">

    function drawChart() {
        // Define the chart to be drawn.
        var data = google.visualization.arrayToDataTable([
            ['Percentile', '', { role: 'style'}, { role: 'annotation' }],
            ['<70',  @Model.one, '#FF0000', ''],
            ['70-75',  @Model.two, '#CC0033', ''],
            ['75-80',  @Model.three, '#990066', ''],
            ['80-85',  @Model.four, '#660099', ''],
            ['85-90',  @Model.five, '#3300CC', ''],
            ['90-95',  @Model.six, '#0000FF', ''],
            ['95-100',  @Model.seven, '#000080', '']
        ]);

        var options = {
        title: 'Average: @Model.average',
        legend: {position: 'none'}
        }; 

        // Instantiate and draw the chart.
        var chart = new google.visualization.ColumnChart(document.getElementById('container'));
        chart.draw(data, options);
     }
    google.charts.setOnLoadCallback(drawChart);
</script>